version: "3" # docker-composeのバージョンを指定
services:
  mysql:
    container_name: stuinfo_db
    build:
      context: ./
      dockerfile: ./mysql.Dockerfile
    ports:
      - "3307:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_DATABASE: student
      MYSQL_ROOT_PASSWORD: root
    cap_add:
      - SYS_NICE
    volumes:
      - "./mysql:/docker-entrypoint-initdb.d"
    networks:
      - stuinfo-mysql-network

  adminer:
    image: adminer:4.6
    container_name: "adminer"
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    networks:
      - stuinfo-mysql-network

networks:
  stuinfo-mysql-network:
    driver: bridge
