@startuml class_diagram

class user{
    name:String
    sex:String
    age:int
    Password:String
    Id:int
}


class Readingrecord{
    janru:String
    privacy:String
    Thinking:String
    ISBN:String
    title:String
    review:int
}



' 関係を定義 
left to right direction
user "1" --- "0...*" Readingrecord:"▼登録する"

' umlの終了を宣言
@enduml